# Generated by Django 2.2.4 on 2019-11-12 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=10, unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_disabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('multimedia', models.FileField(upload_to='banner/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Multimedias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ImageField(upload_to='')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Secciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=10, unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_disabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('subtitulo', models.CharField(max_length=150, verbose_name='Subtítulo')),
                ('orientacion', models.BooleanField(choices=[(False, 'Izquierda'), (True, 'Derecha')], default=True, verbose_name='Orientación')),
                ('media', models.ManyToManyField(related_name='media_secciones', to='page.Multimedias')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=10, unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_disabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.CharField(max_length=150)),
                ('media', models.ManyToManyField(related_name='media_noticias', to='page.Multimedias')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Loginfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('accion', models.CharField(max_length=50)),
                ('folio_objeto', models.CharField(max_length=10)),
                ('tipo_objeto', models.CharField(max_length=50)),
                ('mensaje', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=10, unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_disabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('media', models.ManyToManyField(related_name='media_eventos', to='page.Multimedias')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Asesorias_Tramites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=10, unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_disabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=150)),
                ('media', models.ManyToManyField(related_name='media_asesorias', to='page.Multimedias')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
