# Generated by Django 2.2.4 on 2019-10-23 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Secciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=10)),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=150)),
                ('orientacion', models.BooleanField(choices=[(True, 'Derecha'), (False, 'Izquierda')], default=True)),
                ('imagen', models.ImageField(upload_to='secciones/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='created_sections', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='deleted_sections', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='updated_sections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=10)),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.CharField(max_length=150)),
                ('imagen', models.ImageField(upload_to='noticias/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='created_news', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='deleted_news', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='updated_news', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=10)),
                ('titulo', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('imagen', models.ImageField(upload_to='eventos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='deleted_events', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='updated_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multimedia', models.FileField(upload_to='banner/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='created_banner', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='deleted_banner', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='updated_banner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asesorias_Tramites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=10)),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=150)),
                ('imagen', models.ImageField(upload_to='asesorias_tramites/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='created_advice', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='deleted_advice', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='updated_advice', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
