# Generated by Django 2.2.4 on 2019-10-24 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesorias_tramites',
            name='deleted_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_advice', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asesorias_tramites',
            name='updated_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_advice', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='banner',
            name='deleted_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_banner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='banner',
            name='updated_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_banner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='deleted_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='updated_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='deleted_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_news', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='updated_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_news', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='secciones',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='secciones',
            name='deleted_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_sections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='secciones',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='secciones',
            name='updated_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_sections', to=settings.AUTH_USER_MODEL),
        ),
    ]
