# Generated by Django 2.2.4 on 2019-11-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20191113_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asesorias_tramites',
            name='subtitulo',
        ),
        migrations.AddField(
            model_name='asesorias_tramites',
            name='contenido',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='asesorias_tramites',
            name='extra',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='asesorias_tramites',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='secciones',
            name='subtitulo',
            field=models.CharField(max_length=80, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='secciones',
            name='titulo',
            field=models.CharField(max_length=30, verbose_name='Título'),
        ),
    ]
