# Generated by Django 2.2.4 on 2019-11-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20191114_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesorias_tramites',
            name='contenido',
            field=models.CharField(default='', max_length=200, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='asesorias_tramites',
            name='extra',
            field=models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='Contenido extra'),
        ),
        migrations.AlterField(
            model_name='asesorias_tramites',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='contenido',
            field=models.CharField(max_length=150, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
