# Generated by Django 2.2.4 on 2019-11-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20191115_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='lugar',
            field=models.CharField(default='', max_length=50),
        ),
    ]
