# Generated by Django 2.2.4 on 2019-11-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_auto_20191119_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='hora',
            field=models.TimeField(default='00:00', verbose_name='Hora'),
        ),
    ]
