# Generated by Django 2.2.4 on 2019-11-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_auto_20191119_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='hora',
            field=models.TimeField(verbose_name='Hora'),
        ),
    ]
