# Generated by Django 2.2.4 on 2019-11-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_auto_20191119_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='lugar',
            field=models.CharField(max_length=50, verbose_name='Lugar'),
        ),
    ]
