# Generated by Django 2.2.4 on 2020-03-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_auto_20191119_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='secciones',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
