# Generated by Django 2.2.4 on 2020-03-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_secciones_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='secciones',
            name='boton',
            field=models.BooleanField(default=False, verbose_name='Activar botón'),
        ),
        migrations.AddField(
            model_name='secciones',
            name='link_boton',
            field=models.URLField(blank=True, null=True, verbose_name='Link del botón'),
        ),
        migrations.AddField(
            model_name='secciones',
            name='txt_boton',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Texto del botón'),
        ),
        migrations.AlterField(
            model_name='secciones',
            name='top',
            field=models.BooleanField(default=False, verbose_name='Fijar al principio'),
        ),
    ]
